config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, except: [:show]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :labels, only: %i[new create]
  resources :tasks do
    collection do
      get :sort
      get :search
    end
  end
  root to: 'users#new'
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :content, null:false, presence: true, length: { minimum: 1 }

  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings, source: :label
  enum status: {
                started: 0,
                pending: 1,
                completed: 2
                }
  enum priority: {
                  low: 0,
                  medium: 1,
                  high: 2
                  }
      scope :label_sort, -> (search_label){
                    tasks = Labeling.where(label_id: search_label)
                    ids = tasks.map{ |task| task.task_id }
                    where(id: ids)
                }
      scope :ordered, -> { order(created_at: :desc) }
      scope :orderByDeadline, -> {order(deadline: :desc) }
      scope :orderByPriority, -> {order(priority: :desc) }
      scope :status_sort, -> (search_status){ where(status: search_status) }
      scope :search_sort, -> (search_word){ where('title LIKE ?', "%#{search_word}%") }
      scope :priority_sort, -> (search_priority){ where(priority: search_priority) }
      scope :sort_expired, -> { order(deadline: :desc) }
      # kaminari関連
      scope :kaminari, -> (kaminari_page){ page(kaminari_page).per(5) }
      scope :current_user_sort,->(current_user_id){where(user_id: current_user_id)}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    if params[:sort_expired]
      @tasks=current_user.tasks.orderByDeadline.kaminari(params[:page])
    else
      @tasks=current_user.tasks.ordered.kaminari(params[:page])
    end
    @user=current_user
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @label = @task.labelings.build
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  # GET /tasks/1/edit
  def edit
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def sort
    @tasks = researched.ordered
    @search_title = session[:search]['title'] if session[:search].present?
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    session[:search] = nil
    render :index
  end

  def search
    session[:search] = {'title' => params[:search_title], 'status' => params[:search_status], 'priority' => params[:search_priority]}
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    @tasks = researched.ordered
    @search_title = session[:search]['title']
    render :index
  end

  def researched
    if session[:search].present?
      # If all searches are empty
      if session[:search]['title'].blank? && session[:search]['label'].blank? && session[:search]['status'].blank? && session[:search]['priority'].blank?
        Task.current_user_sort(current_user.id).kaminari(params[:page])

        # The title has been entered
      elsif session[:search]['title'].present?
        # If status, priority were specified
        if session[:search]['status'].present? && session[:search]['priority'].present? && session[:search]['label'].present?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['title']).status_sort(session[:search]['status']).priority_sort(session[:search]['priority']).label_sort(session[:label]['status']).kaminari(params[:page])
          # If only priority and title is specified
        elsif session[:search]['status'].present? && session[:search]['priority'].present?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['title']).status_sort(session[:search]['status'])..label_sort(session[:search]['label']).kaminari(params[:page])
          #If only priority and title are specified
        elsif session[:search]['priority'].present?
          Task.current_user_sort(current_user.id).search_sort(session[:search]['title']).status_sort(session[:search]['priority']).kaminari(params[:page])
        elsif session[:search]['label'].present?
          Task.current_user_sort(current_user.id).title_sort(session[:search]['title']).label_sort(session[:search]['label']).kaminari(params[:page])
        else
          Task.current_user_sort(current_user.id).search_sort(session[:search]['title']).kaminari(params[:page])
        end


        # The title is empty and the status is specified
      elsif session[:search]['status'].present?
        # If priority and status are specified
        if session[:search]['label'].present? && session[:search]['priority'].present?
          Task.current_user_sort(current_user.id).status_sort(session[:search]['status']).priority_sort(session[:search]['priority']).label_sort(session[:search]['label']).kaminari(params[:page])
          # If only priority is specified
        elsif session[:search]['priority'].present?
          Task.current_user_sort(current_user.id).priority_sort(session[:search]['priority']).status_sort(session[:search]['status']).kaminari(params[:page])
        elsif session[:search]['label'].present?
          Task.current_user_sort(current_user.id).label_sort(session[:search]['label']).status_sort(session[:search]['status']).kaminari(params[:page])
        else
          Task.current_user_sort(current_user.id).status_sort(session[:search]['status']).kaminari(params[:page])
        end

        #-------------------------
      elsif session[:search]['priority'].present?
        # If priority and status are specified
        if session[:search]['label'].present?
          Task.current_user_sort(current_user.id).label_sort(session[:search]['label']).priority_sort(session[:search]['priority']).kaminari(params[:page])
          # If only priority is specified
        else
          Task.current_user_sort(current_user.id).priority_sort(session[:search]['priority']).kaminari(params[:page])
        end


      elsif session[:search]['label'].present?
        Task.current_user_sort(current_user.id).label_sort(session[:search]['label']).kaminari(params[:page])


      else
        Task.current_user_sort(current_user.id).kaminari(params[:page])
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :priority, :status, label_ids: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <div class="text-center">
      <%= form_with(model: task, local: true) do |f| %>
      <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title ,class:'fs-16' %>
  </div>

  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field form-group">
    <%= f.label :Deadline %>
    <%= f.date_field :deadline, placeholder: 'Deadline' %>
  </div>

  <div class="field status form-group">
    <%= f.label :Status %>
    <%= f.select :status, Task.statuses.keys %>
  </div>

  <div class="field prority form-group">
    <%= f.label :Priority %>
    <%= f.select :priority, Task.priorities.keys %>
  </div>

  <div class="form_labels field form-group">
   <%= f.label :label, 'Etiquettes' %><br>
    <div class="row">
      <% Label.all.each do |label| %>
        <%= f.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
        <%= label.name %>
      <% end %>
    </div>
  </div>

  <div class="actions">
      <%= f.submit "Create Task", class:'btn btn-primary' %> | <%= f.submit "Edit", class:'btn btn-primary' %>
  </div>
<% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task, class: 'btn btn-warning' %> | <%= link_to 'Back', tasks_path, class: 'btn btn-primary' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<style>
  th{
    font-size: 18px;
    border-left: 2px solid black;
    border-top: 2px solid black;
    border-bottom: 2px solid black;
    }
</style>

<h1><%= link_to 'Tasks' ,root_path %></h1>

<div class="container shadow">
 <h1>Tasks List</h1>
 <div class="row py-3">
  <div class="col sm-3">
    <div class="col">
      <%= form_with(url: search_tasks_path, method: :get, local: true) do |f| %>
        <% if defined? @search_title %>
      <%= f.text_field :search_title, value: @search_title ,class:'label mx-3'%>
        <% else %>
      <%= f.text_field :search_title %> |
        <% end %>
      <%= f.select :search_status, Task.statuses.map { |k, v| [k, v] }, class: 'search_status form-control', prompt: 'status'%> |
      <%= f.select :search_priority, Task.priorities.map { |k, v| [k, v] }, class: 'search_priority form-control', prompt: 'priority'%> |
      <%= f.select :search_label, @labels.collect { |p| [p.name, p.id]}, class: "search_label", prompt: 'Tag' %> |
      <%= f.submit 'search',class:'btn btn-light fs-15' %>
        <% end %>
     </div>
   </div>
 </div>

  <div class="container py-3">
    <%= link_to 'New Task', new_task_path ,class: 'btn btn-primary text-light'%> |
    <%= link_to 'New Label', new_label_path, class:'btn btn-outline-warning' %> |
    <%= link_to "sort by end deadline", tasks_path(sort_expired: "true"), class: 'col btn btn-secondary text-light' %>
  </div>
  <table class="table">
     <thead>
       <tr>
        <th>Author</th>
        <th>Title</th>
        <th>Content</th>
        <th>Deadline</th>
        <th>Registered at</th>
        <th>Status</th>
        <th>Priority</th>
        <th>Admin/User</th>
        <th>Tag</th>
        <th colspan="4"></th>
       </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
           <td><%= current_user.name %></td>
           <td class="task_row task_title"><%= link_to task.title, task_path(task.id) %></td>
           <td><%= task.content %></td>
           <td><%= task.deadline %></td>
           <td><%= task.created_at %></td>
           <td><%= task.status %></td>
           <td><%= task.priority %></td>
           <td><%= User.find(task.user_id).name%></td>
           <td>
              <% task.labels.each do |label| %>
                [<%= label.name %>]
              <% end %>
          </td>
           <td><%= link_to 'Show', task, class:'btn btn-outline-primary'%></td>
           <td><%= link_to 'Edit', edit_task_path(task), class:'btn btn-outline-warning' %></td>
           <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger' %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
    <br>
    <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Back', tasks_path,class:'btn btn-primary' %>

app/views/tasks/show.html.erb
<style>
  strong{
    font-size: 20px;
    font-family: fantasy;
    color: black;
  }
  span{
    color: black;
    font-size: 18px;
    font-family: 'Lucida';
  }
</style>

<div class="container">
    <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @task.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @task.content %>
  </p>
  <p>
    <strong>Deadline:</strong>
    <%= @task.deadline %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= @task.status %>
  </p>
  <p>
    <strong>Priority:</strong>
    <%= @task.priority %>
  </p>
  <p>
    <strong>Etiquettes associés : </strong>
      <% if @task.labels.present? %>
      <% @task.labels.each do |l| %>
  <span class="label"><%= l.name %></span>
      <% end %>
      <% end %>
  </p>

    <%= link_to 'Edit', edit_task_path(@task), class:'fs-20 btn btn-primary' %> |
    <%= link_to 'Back', tasks_path, class:'fs-20 btn btn-warning' %>

</div>