config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, except: [:show]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :labels, only: %i[new create]
  resources :tasks do
    collection do
      get :sort
      get :search
    end
  end
  root to: 'users#new'
end

app/views/layouts/application.html.erb
<p id="notice"><%= notice %></p>
<!DOCTYPE html>
<html>
  <head>
    <title>ManyocoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <style>
     p ,h1,label,button,th,td{
        color: white;
     }
     td{
       font-family: cursive;
       font-size: 15px;
     }
     select{
       padding: 10px;
     }
     label{
       font-size: 20px;
       margin-bottom: 5px;
       text-decoration: underline;
       float: left;
     }
   </style>
  <body style="background-color: #8897e3;font-family:Verdana">
    <header class="header shadow">
      <ul class="nav justify-content-center bg-white">
          <% if logged_in? %>
        <li>
      | | <%= link_to 'Tasks', tasks_path ,class:'fs-20 btn btn-primary text-light'%> |
          <%= link_to 'MyPage', user_path(current_user.id) ,class:'btn fs-20 btn-secondary text-light'%> |
          <%= link_to 'Logout', session_path(current_user.id), method: :delete, data: {confirm: 'Are you sure you want to log out?'} ,class:'btn fs-20 btn-secondary text-light'%> | |
          <% if current_user.admin? %>
          <%= link_to 'Management', admin_users_path ,class:'btn fs-20 btn-outline-dark'%>
        </li>
          <% end %>
          <% else %>
        <li>
          <%= link_to 'User registration', new_user_path ,class:'btn btn-outline-primary fs-20'%>
        </li>
        <li>
          <%= link_to 'Login', new_session_path,class:'btn btn-outline-warning fs-20' %>
        </li>
          <% end %>
          <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
          <%end%>
      </ul>
    </header>
<%= yield %>
  </body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  <div class="card-footer text-center" style="position: fixed;
          left: 0;
          bottom: 0;
          height: 15px;
          width: 100%;
          color: white;
          padding-top: 0px;
          padding-bottom: 16px;
          border-top-width: 0px;
          text-align: center;">
    <div class="nav justify-content-center">
      <footer class="Copyright"><p class="text-footer fs-10">Copirigth &copy All rigths reserved & middot</p></footer>
  </div>
  </div>
</html>